name = "Trần Viet hung"
print(name)
print("capitalize: ".ljust(13, "_"), name.capitalize())
print("upper: ".ljust(13, "_"), name.upper())
print("lower: ".ljust(13, "_"), name.lower())
print("swapcase: ".ljust(13, "_"), name.swapcase())
print("title: ".ljust(13, "_"), name.title())
print("center: ".ljust(13, "_"), name.center(30, "*"))
print("rjust: ".ljust(13, "_"), name.rjust(30, "*"))
print("ljust: ".ljust(13, "_"), name.ljust(30, "*"))
print("encode: ".ljust(13, "_"), name.encode())
print("join: ".ljust(13, "_"), name.join(["1", "2", "3"]))
print("strip: ".ljust(13, "_"), name.strip(" "))
print("rstrip: ".ljust(13, "_"), name.rstrip(" "))
print("lstrip: ".ljust(13, "_"), name.lstrip(" "))
